version: '3.9'

services:
  web:
    build: . 
    volumes:
      - .static/captured_images:/app/static/captured_images
      # django <-> docker
      # :/app/static/captured_images stand for docker 
      # docker Volume -> ( path that you want to store data-> :/app/static/captured_images)
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

volumes:
  db_data:
